/* eslint-disable */

import { createSlice, type PayloadAction } from "@reduxjs/toolkit";
import { SupervisorCoderAgentTask } from "../../util/types/taskAgent";
import { StreamComponent } from "../../util/types/stream-component";
 
// New message component structure
export type MessageComponent = {
  type: string;           // Component type identifier
  props: Record<string, any>; // Props for the component
};


/**
 * Message structure in database and state
 */
export type ChatMessage = {
  message_id?: string;
  chat_session_id: string;
  role: "User" | "AI";
  content: string | null;
  created_at: string;
  is_streaming?: boolean;
  //is_typewriter?: boolean;
  hidden?: boolean;
  components?: StreamComponent[] //MessageComponent // | ToolCallComponent[];
};

export type ChatMessageObj = ChatMessage & {
  is_typewriter: boolean;
  // NEW: can hold any rendered UI
  // content_component?: ChatContentComponentType
};

export type StreamingState = {
	isStreaming: boolean;
	currentEvent: any;
	currentStatus:
		| "idle"
		| "planning"
		| "thinking"
		| "coding"
		| "building"
		| "deploying"
		| "pushing_migration"
    | "generating_tasks";
	currentAiMessage: string;
	isReceivingAiMessage: boolean;
	streamingMessageId: string | null; // ID of the current streaming message
	toolCalls: Array<{
		id: string;
		name: string;
		status: "start" | "streaming" | "complete";
		args: Record<string, unknown>;
		partialContent: string;
	}>;
  taskList: SupervisorCoderAgentTask[]; //List of tasks generated by task agent 
	buildStatus: "idle" | "building" | "success" | "failed";
	deployStatus: "idle" | "deploying" | "success" | "failed";
	refreshingPreview: boolean;
	error: string | null;
};

interface ChatSessionState {
  messages: ChatMessageObj[];
  pagination: {
    hasMore: boolean;
    nextCursor?: string;
    loading: boolean;
    loadingMore: boolean;
  };
  error: string | null;

}

interface ChatState {
  sessions: Record<string, ChatSessionState>;
  streamingStates: Record<string, StreamingState>;
  isProductChatLoading: boolean;
}

const initialStreamingState: StreamingState = {
  isStreaming: false,
  currentEvent: null,
  currentStatus: "idle",
  currentAiMessage: "",
  isReceivingAiMessage: false,
  streamingMessageId: null,
  taskList: [],
  toolCalls: [],
  buildStatus: "idle",
  deployStatus: "idle",
  refreshingPreview: false,
  error: null,
};

const initialSessionState: ChatSessionState = {
  messages: [],
  pagination: {
    hasMore: true,
    loading: false,
    loadingMore: false,
  },
  error: null,
 
};

const initialState: ChatState = {
  sessions: {},
  streamingStates: {},
  isProductChatLoading: false
};

const chatSlice = createSlice({
  name: "chat",
  initialState,
  reducers: {
    // Session management
    initializeSession: (state, action: PayloadAction<string>) => {
      const sessionId = action.payload;
      if (!state.sessions[sessionId]) {
        state.sessions[sessionId] = { ...initialSessionState };
      }
      if (!state.streamingStates[sessionId]) {
        state.streamingStates[sessionId] = { ...initialStreamingState };
      }
    },

    // Messages management
    setMessages: (
      state,
      action: PayloadAction<{
        sessionId: string;
        messages: ChatMessageObj[];
        replace?: boolean;
      }>,
    ) => {
      const { sessionId, messages, replace = false } = action.payload;
      if (!state.sessions[sessionId]) {
        state.sessions[sessionId] = { ...initialSessionState };
      }

      if (replace) {
        const sortedMessages = [...messages].sort(
          (a, b) =>
            new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
        );
        state.sessions[sessionId].messages = sortedMessages;
      } else {
        const existingMessages = state.sessions[sessionId].messages;
        const allMessages = [...existingMessages, ...messages];

        // Remove duplicates based on message_id
        const uniqueMessages = allMessages.filter((message, index, arr) =>
          message.message_id
            ? arr.findIndex((m) => m.message_id === message.message_id) ===
              index
            : true,
        );

        const sortedMessages = [...uniqueMessages].sort(
          (a, b) =>
            new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
        );
        state.sessions[sessionId].messages = sortedMessages;
      }
    },

    addMessage: (
      state,
      action: PayloadAction<{ sessionId: string; message: ChatMessageObj }>,
    ) => {
      const { sessionId, message } = action.payload;
      if (!state.sessions[sessionId]) {
        state.sessions[sessionId] = { ...initialSessionState };
      }

      const session = state.sessions[sessionId];

      // Check for existing message by message_id
      if (message.message_id) {
        const existingIndex = session.messages.findIndex(
          (m) => m.message_id === message.message_id,
        );

        if (existingIndex >= 0) {
          // Update existing message
          session.messages[existingIndex] = message;
        } else {
          // Add new message
          session.messages.push(message);
        }
      } else {
        // Add message without ID
        session.messages.push(message);
      }

      // Keep messages sorted
      const sortedMessages = [...session.messages].sort(
        (a, b) =>
          new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
      );
      session.messages = sortedMessages;
    },

    updateMessage: (
      state,
      action: PayloadAction<{
        sessionId: string;
        messageId: string;
        updates: Partial<ChatMessageObj>;
      }>,
    ) => {
      const { sessionId, messageId, updates } = action.payload;
      const session = state.sessions[sessionId];
      //console.log("[lib/redux/features/chatSlice]:[updateMessage] Arguments: ", sessionId, messageId, updates)
      if (session) {
        const messageIndex = session.messages.findIndex(
          (m) => m.message_id === messageId,
        );
        // console.log("[Message index found]", messageIndex)
        // console.log("[Session Messages]", [...session.messages]);
        
        if (messageIndex >= 0) {
          // console.log(
          //   "[Specific Message Before Update]",
          //   { ...session.messages[messageIndex] }
          // );
    
          session.messages[messageIndex] = {
            ...session.messages[messageIndex],
            ...updates,
          };
          // Log after updating
          // console.log(
          //   "[Specific Message After Update]",
          //   { ...session.messages[messageIndex] }
          // );
        }
      }
    },

    removeMessage: (
      state,
      action: PayloadAction<{ sessionId: string; messageId: string }>,
    ) => {
      const { sessionId, messageId } = action.payload;
      const session = state.sessions[sessionId];

      if (session) {
        session.messages = session.messages.filter(
          (m) => m.message_id !== messageId,
        );
      }
    },

    // Pagination management
    setPagination: (
      state,
      action: PayloadAction<{
        sessionId: string;
        pagination: Partial<ChatSessionState["pagination"]>;
      }>,
    ) => {
      const { sessionId, pagination } = action.payload;
      if (!state.sessions[sessionId]) {
        state.sessions[sessionId] = { ...initialSessionState };
      }

      state.sessions[sessionId].pagination = {
        ...state.sessions[sessionId].pagination,
        ...pagination,
      };
    },

    // Error management
    setError: (
      state,
      action: PayloadAction<{ sessionId: string; error: string | null }>,
    ) => {
      const { sessionId, error } = action.payload;
      if (!state.sessions[sessionId]) {
        state.sessions[sessionId] = { ...initialSessionState };
      }

      state.sessions[sessionId].error = error;
    },

    // Streaming state management
    setStreamingState: (
      state,
      action: PayloadAction<{
        sessionId: string;
        streamingState: Partial<StreamingState>;
      }>,
    ) => {
      const { sessionId, streamingState } = action.payload;
      if (!state.streamingStates[sessionId]) {
        state.streamingStates[sessionId] = { ...initialStreamingState };
      }

      state.streamingStates[sessionId] = {
        ...state.streamingStates[sessionId],
        ...streamingState,
      };
    },

    resetStreamingState: (state, action: PayloadAction<string>) => {
      const sessionId = action.payload;
      state.streamingStates[sessionId] = { ...initialStreamingState };
    },

    // Clear session data
    clearSession: (state, action: PayloadAction<string>) => {
      const sessionId = action.payload;
      delete state.sessions[sessionId];
      delete state.streamingStates[sessionId];
    },
    setProductChatLoading: (state, action: PayloadAction<boolean>) => {
			state.isProductChatLoading = action.payload;
		},
  },
});

export const {
  initializeSession,
  setMessages,
  addMessage,
  updateMessage,
  removeMessage,
  setPagination,
  setError,
  setStreamingState,
  resetStreamingState,
  clearSession,
  setProductChatLoading
} = chatSlice.actions;

export default chatSlice.reducer;
