import React from "react";
import { Code2, Database } from "lucide-react";
import { type LandingStyle } from "./landingStyle";

const ownershipCards = [
  {
    icon: <Code2 className="text-orange-400" size={28} />,
    title: "Complete Code Ownership",
    description:
      "You own every line of code Cognix generates. Export to your own GitHub repository anytime, no lock-in, no strings attached.",
  },
  {
    icon: <Database className="text-orange-400" size={28} />,
    title: "Complete Data & Database Ownership",
    description:
      "Your data stays yours. Full access to your Supabase project, schema, and all data. We never hold or monetize your database.",
  },
];

interface OwnershipProps {
  styleVariant?: LandingStyle;
}

export default function Ownership({ styleVariant = "swiss" }: OwnershipProps) {
  if (styleVariant === "beta") {
    return (
      <section id="ownership" className="bg-background py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <h2 className="mb-6 text-3xl font-bold text-foreground md:text-5xl">
              Full Ownership of Your Application
            </h2>
            <p className="mx-auto max-w-2xl text-lg text-muted-foreground">
              You own your application and all the code generated by Cognix. You can export the code to your own repository anytime.
            </p>
          </div>

          <div className="mx-auto grid max-w-4xl gap-8 md:grid-cols-2">
            {ownershipCards.map((card) => (
              <div
                key={card.title}
                className="group relative rounded-2xl border border-border bg-card p-8 shadow-[0_25px_70px_rgba(3,3,10,0.12)] transition-all duration-300 hover:border-brand-primary/40"
              >
                <div className="mb-6 w-fit rounded-xl border border-brand-border bg-brand-primary/10 p-3 transition-colors group-hover:border-brand-primary/40">
                  {card.icon}
                </div>
                <h3 className="mb-3 text-xl font-semibold text-foreground">
                  {card.title}
                </h3>
                <p className="leading-relaxed text-muted-foreground">
                  {card.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  if (styleVariant === "space") {
    return (
      <section id="ownership" className="border-t border-white/10 py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 grid gap-8 border-b border-white/10 pb-10 lg:grid-cols-[220px_minmax(0,1fr)]">
            <div className="text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200/70">
              Ownership
            </div>
            <div>
              <h2 className="mb-6 text-3xl font-black tracking-[-0.05em] text-white md:text-5xl">
                Full Ownership of Your Application
              </h2>
              <p className="max-w-2xl text-lg leading-8 text-slate-300">
                You own your application and all the code generated by Cognix. You
                can export the code to your own repository anytime.
              </p>
            </div>
          </div>

          <div className="grid max-w-5xl gap-5 md:mx-auto md:grid-cols-2">
            {ownershipCards.map((card) => (
              <div
                key={card.title}
                className="rounded-[28px] border border-white/10 bg-slate-950/55 p-8 backdrop-blur-xl"
              >
                <div className="mb-8 w-fit rounded-2xl border border-white/10 bg-white/5 p-3">
                  {card.icon}
                </div>
                <h3 className="mb-3 text-xl font-semibold text-white">{card.title}</h3>
                <p className="leading-8 text-slate-400">{card.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="ownership" className="border-t border-border bg-background py-24">
      <div className="mx-auto max-w-7xl px-6">
        <div className="mb-16 grid gap-8 border-b border-border pb-10 lg:grid-cols-[220px_minmax(0,1fr)]">
          <div className="text-xs font-semibold uppercase tracking-[0.24em] text-muted-foreground">
            Ownership
          </div>
          <div>
            <h2 className="mb-6 text-3xl font-black uppercase tracking-[-0.05em] text-foreground md:text-5xl">
              Full Ownership of Your Application
            </h2>
            <p className="max-w-2xl text-lg leading-8 text-muted-foreground">
              You own your application and all the code generated by Cognix. You
              can export the code to your own repository anytime.
            </p>
          </div>
        </div>

        <div className="grid max-w-5xl gap-0 border border-border md:mx-auto md:grid-cols-2">
          {ownershipCards.map((card, index) => (
            <div
              key={card.title}
              className="group relative bg-card p-8 transition-all duration-300 hover:bg-muted/50 [&:not(:last-child)]:border-b [&:not(:last-child)]:border-border md:[&:not(:last-child)]:border-b-0 md:[&:not(:last-child)]:border-r"
            >
              <div className="mb-8 flex items-center justify-between">
                <div className="w-fit border border-brand-border bg-brand-primary/10 p-3 transition-colors group-hover:border-brand-primary/40">
                  {card.icon}
                </div>
                <div className="text-xs font-semibold uppercase tracking-[0.24em] text-muted-foreground">
                  0{index + 1}
                </div>
              </div>
              <h3 className="mb-3 text-xl font-semibold text-foreground">
                {card.title}
              </h3>
              <p className="leading-8 text-muted-foreground">
                {card.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
