import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  ChevronDown, 
  ChevronRight, 
  Code, 
  CheckCircle2, 
  Circle,
  Server,
  Layout
} from "lucide-react";
import { cn } from "../lib/utils";
import { SupervisorCoderAgentTask } from "../lib/util/types/taskAgent";

interface TaskListProps {
  tasks: SupervisorCoderAgentTask[];
  totalTasks: number;
  isStreaming?: boolean;
  animationDelay?: number;
}

/**
 * @description Display to user the list of tasks generated, mainly show instructions and context and file dependencies.
 * @param tasks List of tasks generated by task agent on AI server 
 * @returns 
 */
export function TaskList({ 
  tasks, 
  totalTasks, 
  isStreaming = false,
  animationDelay = 0 
}: TaskListProps) {
  const [expandedTasks, setExpandedTasks] = useState<Set<number>>(new Set());
  const [expandedSubtasks, setExpandedSubtasks] = useState<Set<string>>(new Set());

  const toggleTask = (index: number) => {
    const newExpanded = new Set(expandedTasks);
    if (newExpanded.has(index)) {
      newExpanded.delete(index);
    } else {
      newExpanded.add(index);
    }
    setExpandedTasks(newExpanded);
  };

  const toggleSubtask = (taskIndex: number, subtaskIndex: number) => {
    const key = `${taskIndex}-${subtaskIndex}`;
    const newExpanded = new Set(expandedSubtasks);
    if (newExpanded.has(key)) {
      newExpanded.delete(key);
    } else {
      newExpanded.add(key);
    }
    setExpandedSubtasks(newExpanded);
  };

  const getTaskIcon = (type: string) => {
    switch (type) {
      case "Backend": return <Server className="w-4 h-4" />;
      case "Frontend": return <Layout className="w-4 h-4" />;
      case "Fullstack": return <Code className="w-4 h-4" />;
      default: return <Code className="w-4 h-4" />;
    }
  };

  const getTaskColor = (type: string) => {
    switch (type) {
      case "Backend": return "bg-blue-500/10 text-blue-500 border-blue-500/20";
      case "Frontend": return "bg-purple-500/10 text-purple-500 border-purple-500/20";
      case "Fullstack": return "bg-green-500/10 text-green-500 border-green-500/20";
      default: return "bg-gray-500/10 text-gray-500 border-gray-500/20";
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, delay: animationDelay }}
      className="rounded-lg border border-border bg-card p-4 space-y-3"
    >
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="w-5 h-5 text-green-500" />
          <h3 className="font-semibold text-sm">Implementation Tasks</h3>
        </div>
        <span className="text-xs text-muted-foreground">
          {totalTasks} task{totalTasks !== 1 ? 's' : ''}
        </span>
      </div>

      {/* Tasks */}
      <div className="space-y-2">
        {tasks.map((task, index) => (
          <div key={index} className="border border-border rounded-md overflow-hidden">
            {/* Task Header */}
			<button
			onClick={() => toggleTask(index)}
			className="w-full flex items-center gap-3 p-3 hover:bg-navbar/60 transition-colors"
			>
			{expandedTasks.has(index) ? (
				<ChevronDown className="w-4 h-4 text-muted-foreground" />
			) : (
				<ChevronRight className="w-4 h-4 text-muted-foreground" />
			)}
			<div className={cn(
				"flex items-center gap-2 px-2 py-1 rounded border text-xs font-medium",
				getTaskColor(task.type)
			)}>
				{getTaskIcon(task.type)}
				{task.type}
			</div>
			<div className="flex-1 text-left">
				<p className={cn(
				"text-sm font-medium",
				expandedTasks.has(index) ? "" : "line-clamp-1"
				)}>
				{expandedTasks.has(index) 
					? task.instructions.split('\n')[0]
					: task.instructions.split('\n')[0].substring(0, 80) + (task.instructions.split('\n')[0].length > 80 ? '...' : '')
				}
				</p>
			</div>
			{task.subtasks.length > 0 && (
				<span className="text-xs text-muted-foreground">
				{task.subtasks.length} subtask{task.subtasks.length !== 1 ? 's' : ''}
				</span>
			)}
			</button>

            {/* Expanded Content */}
            <AnimatePresence>
              {expandedTasks.has(index) && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="border-t border-border bg-muted/30 p-4"
                >
                  {/* Instructions */}
                  <div className="mb-3">
                    <h4 className="text-xs font-semibold text-muted-foreground mb-2">
                      Instructions
                    </h4>
					{/* Instruction Summary for Parent Task */}
					{task.instruction_summary && task.instruction_summary.length > 0 && (
						<div className="mb-3">
							<ul className="space-y-1 text-sm">
								{task.instruction_summary.map((point, i) => (
								<li key={i} className="flex items-start gap-2">
									<span className="text-muted-foreground mt-1.5">•</span>
									<span className="flex-1">{point}</span>
								</li>
								))}
							</ul>
						</div>
					)}
                    {/* <p className="text-sm whitespace-pre-wrap">
                      {task.instructions}
                    </p> */}
                  </div>

                  {/* Context */}
                  {/* {task.context.task_context && (
                    <div className="mb-3">
                      <h4 className="text-xs font-semibold text-muted-foreground mb-2">
                        Context
                      </h4>
                      <p className="text-sm text-muted-foreground">
                        {task.context.task_context}
                      </p>
                    </div>
                  )} */}

                  {/* File Dependencies */}
                  {/* {task.context.file_dependencies.length > 0 && (
                    <div className="mb-3">
                      <h4 className="text-xs font-semibold text-muted-foreground mb-2">
                        Dependencies
                      </h4>
                      <div className="flex flex-wrap gap-1">
                        {task.context.file_dependencies.map((file, i) => (
                          <span
                            key={i}
                            className="text-xs bg-background px-2 py-1 rounded border"
                          >
                            {file}
                          </span>
                        ))}
                      </div>
                    </div>
                  )} */}

                  {/* Subtasks */}
                  {task.subtasks.length > 0 && (
                    <div className="mt-4 pt-4 border-t border-border">
                      <h4 className="text-xs font-semibold text-muted-foreground mb-2">
                        Subtasks ({task.subtasks.length})
                      </h4>
                      <div className="space-y-2">
                        {task.subtasks.map((subtask, subtaskIndex) => {
                          const subtaskKey = `${index}-${subtaskIndex}`;
                          const isExpanded = expandedSubtasks.has(subtaskKey);
                          
                          return (
                            <div 
                              key={subtaskIndex} 
                              className="border border-border/50 rounded bg-background/50"
                            >
                              {/* Subtask Header */}
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  toggleSubtask(index, subtaskIndex);
                                }}
                                className="w-full flex items-center gap-2 p-2 hover:bg-accent/30 transition-colors"
                              >
                                {isExpanded ? (
                                  <ChevronDown className="w-3 h-3 text-muted-foreground flex-shrink-0" />
                                ) : (
                                  <ChevronRight className="w-3 h-3 text-muted-foreground flex-shrink-0" />
                                )}
                                <Circle className="w-3 h-3 text-muted-foreground flex-shrink-0" />
                                <span className="text-xs font-medium text-left flex-1">
                                  {subtask.instructions.split('\n')[0].substring(0, 60)}
                                  {subtask.instructions.length > 60 ? '...' : ''}
                                </span>
                              </button>

                              {/* Subtask Expanded Content */}
                              <AnimatePresence>
                                {isExpanded && (
                                  <motion.div
                                    initial={{ height: 0, opacity: 0 }}
                                    animate={{ height: "auto", opacity: 1 }}
                                    exit={{ height: 0, opacity: 0 }}
                                    className="border-t border-border/50 bg-muted/20 p-3 space-y-2"
                                  >
                                    {/* Subtask Instructions */}
                                    <div>
                                      <p className="text-xs text-muted-foreground font-semibold mb-1">
                                        Instructions
                                      </p>
                                      <p className="text-xs whitespace-pre-wrap">
                                        {subtask.instructions}
                                      </p>
                                    </div>

                                    {/* Subtask Context */}
                                    {subtask.context.task_context && (
                                      <div>
                                        <p className="text-xs text-muted-foreground font-semibold mb-1">
                                          Context
                                        </p>
                                        <p className="text-xs text-muted-foreground">
                                          {subtask.context.task_context}
                                        </p>
                                      </div>
                                    )}

                                    {/* Subtask Dependencies */}
                                    {subtask.context.file_dependencies.length > 0 && (
                                      <div>
                                        <p className="text-xs text-muted-foreground font-semibold mb-1">
                                          Dependencies
                                        </p>
                                        <div className="flex flex-wrap gap-1">
                                          {subtask.context.file_dependencies.map((file, i) => (
                                            <span
                                              key={i}
                                              className="text-xs bg-background px-1.5 py-0.5 rounded border text-muted-foreground"
                                            >
                                              {file}
                                            </span>
                                          ))}
                                        </div>
                                      </div>
                                    )}
                                  </motion.div>
                                )}
                              </AnimatePresence>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        ))}
      </div>
    </motion.div>
  );
}