export const SUPABASE_URL = "SUPABASE_URL"
export const SUPABASE_ANON_KEY = "SUPABASE_ANON_KEY"
export const SUPABASE_SERVICE_KEY = "SUPABASE_SERVICE_KEY"
 
export const NEXT_PUBLIC_SUPABASE_URL = "NEXT_PUBLIC_SUPABASE_URL"
export const NEXT_PUBLIC_SUPABASE_ANON_KEY = "NEXT_PUBLIC_SUPABASE_ANON_KEY"
export const NEXT_SUPABASE_SERVICE_KEY = "NEXT_SUPABASE_SERVICE_KEY"
 
export const SUPABASE_SECRET_KEYS = [SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_KEY]
export const NEXTJS_SECRET_KEYS = [NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, NEXT_SUPABASE_SERVICE_KEY]
